rspbMapSmart:
  - map:
      schema: dbo
      table: test
      column: id
      category: cat1
      attribute: at1
      type: NUMERIC
  - map:
      schema: dbo
      table: test
      column: name
      category: cat1
      attribute: at2
      type: TEXT
  - map:
      schema: dbo
      table: test
      column: name
      category: cat1
      attribute: at3
      type: LIST
  - map:
      schema: dbo
      table: test
      column: name
      category: cat2
      attribute: at4
      type: BOOLEAN
  - map:
      schema: dbo
      table: test
      column: name
      category: cat2
      attribute: at5
      type: DATE
  - map:
      schema: dbo
      table: test
      column: name
      category: cat2
      attribute: at6
      type: TREE
  - map:
      schema: dbo
      table: test
      column: name
      category: cat3
      attribute: at7
      type: TEXT